### PR TITLE
Add SLES support

### PR DESCRIPTION
**Pull request by turkenh**
Tested with:
SLES11 SP2
SLES11 SP3
SLES11 SP4
SLES12
SLES12 SP1

### CODE REVIEW

**Comment by turkenh** [comment]
Closes #27 
Is there a rough estimate about when SUSE support can be accessible from the role in Galaxy Hub?

**Comment by William-Yeh** [comment]
Within one week.

**Comment by William-Yeh** [comment]
Before merge, I'd like to know: does this applies to openSUSE as well?

**Comment by turkenh** [comment]
Yes, it works with openSUSE too.
Just tested with openSUSE Leap 42.1 (x86_64)

**Pull request merged**
