### PR TITLE
Fixed fetch .tar.gz condition to really fail in Mac

### PR DESCRIPTION
**Pull request by mmannerm**
Also fix the JCE installation in Mac to not require unzip.

### CODE REVIEW

**Comment by trevorr** [comment]
This also fixes the `.tar.gz` condition for yum-based platforms, as currently both the `.rpm` and `.tar.gz` are fetched.

**Comment by eliseshaffer** [comment]
Is there any movement on this pull request? I ma having the same issue from #46 I was wondering if this pull request was going to be accepted or if there is a reason to not accept it?

**Comment by dlethin** [comment]
+1

**Comment by William-Yeh** [comment]
Fixed. Thanks for your contribution.

**Pull request closed without merging**
